/**
 * UNT 2023-style practice test questions: Physics and Mathematics
 * In English (en), Kazakh (kk), and Russian (ru).
 */

export type Lang = 'en' | 'kk' | 'ru'

export interface QuestionI18n {
  id: string
  question: string
  questionKk: string
  questionRu: string
  options: string[]
  optionsKk: string[]
  optionsRu: string[]
  correctAnswer: number
  /** Optional image/diagram for the question (e.g. circuit, path diagram). Path under /images/questions/ */
  imageUrl?: string
}

export const physics2023Questions: QuestionI18n[] = [
  // Q1: Boat/fisherman – distance boat moves (g=10, no water resistance)
  {
    id: 'ph1',
    question: 'A boat rests on the surface of a pond. A fisherman of mass 50 kg in the boat moves from bow to stern. The distance the boat will move relative to the water. Boat mass 200 kg, length 2 m. (Water resistance is zero)',
    questionKk: 'Қайық бөгет бетінде тыныш тұр. Қайықтағы 50 кг балықшы тұмсықтан қақпаға өтеді. Суға қатысты қайық қанша жылжиды? Қайық массасы 200 кг, ұзындығы 2 м. (Су кедергісі нөл)',
    questionRu: 'Лодка покоится на поверхности пруда. Рыбак массой 50 кг, находящийся в лодке, переходит с носа на корму. Расстояние, на которое переместится лодка относительно воды. Масса лодки 200 кг, длина 2 м. (Сила сопротивления воды равна нулю)',
    options: ['1.2 m', '0.9 m', '0.2 m', '1.5 m', '0.4 m'],
    optionsKk: ['1,2 м', '0,9 м', '0,2 м', '1,5 м', '0,4 м'],
    optionsRu: ['1,2 м', '0,9 м', '0,2 м', '1,5 м', '0,4 м'],
    correctAnswer: 2,
  },
  // Q2: Formula for weight on horizontal surface
  {
    id: 'ph2',
    question: 'The formula for determining the weight of a body lying on a horizontal surface',
    questionKk: 'Көлденең бетте жатқан дененің салмағын анықтау формуласы',
    questionRu: 'Формула для определения веса тела, лежащего на горизонтальной поверхности',
    options: ['P = mg', 'm = F/a', 'F = ma', 'F = μN', 'p = F/Δx'],
    optionsKk: ['P = mg', 'm = F/a', 'F = ma', 'F = μN', 'p = F/Δx'],
    optionsRu: ['P = mg', 'm = F/a', 'F = ma', 'F = μN', 'p = F/Δx'],
    correctAnswer: 0,
  },
  // Q3: Aluminum and lead cylinders in mercury – depth ratio
  {
    id: 'ph3',
    question: 'Two solid cylinders, aluminum and lead, of the same mass and diameter float vertically in mercury. The ratio of the immersion depth of the aluminum cylinder to the immersion depth of the lead cylinder is (ρ_lead = 11400 kg/m³, ρ_aluminum = 2700 kg/m³, ρ_mercury = 13.6·10³ kg/m³, g ≈ 9.8 m/s²)',
    questionKk: 'Бірдей масса мен диаметрлі алюминий және қорғасын цилиндрлер сынапта тігінен жүзеді. Алюминий цилиндрдің бату тереңдігінің қорғасын цилиндрдің бату тереңдігіне қатынасы (ρ_қорғасын = 11400 кг/м³, ρ_алюминий = 2700 кг/м³, ρ_сынап = 13,6·10³ кг/м³, g ≈ 9,8 м/с²)',
    questionRu: 'Два сплошных цилиндра — алюминиевый и свинцовый одинаковой массы и диаметра — плавают в вертикальном положении в ртути. Глубина погружения алюминиевого цилиндра к глубине погружения свинцового относятся как (ρ_свинца = 11400 кг/м³, ρ_алюминия = 2700 кг/м³, ρ_ртути = 13,6·10³ кг/м³, g ≈ 9,8 м/с²)',
    options: ['5/1', '3/2', '2/3', '1/5', '1'],
    optionsKk: ['5/1', '3/2', '2/3', '1/5', '1'],
    optionsRu: ['5/1', '3/2', '2/3', '1/5', '1'],
    correctAnswer: 0,
  },
  // Q4: Isothermal compression – work by external forces
  {
    id: 'ph4',
    question: 'During isothermal compression, the gas transferred 600 J of heat to the surroundings. The work performed by external forces is',
    questionKk: 'Изотермиялық сығылғанда газ қоршаған ортаға 600 Дж жылу берді. Сыртқы күштердің орындаған жұмысы',
    questionRu: 'При изотермическом сжатии газ передал окружающим телам количество теплоты 600 Дж. Внешние силы совершили работу',
    options: ['-300 J', '300 J', '0', '-600 J', '600 J'],
    optionsKk: ['-300 Дж', '300 Дж', '0', '-600 Дж', '600 Дж'],
    optionsRu: ['-300 Дж', '300 Дж', '0', '-600 Дж', '600 Дж'],
    correctAnswer: 4,
  },
  // Q5: Two cylinders – isothermal expansion pressure
  {
    id: 'ph5',
    question: 'If a cylinder containing 12 L of oxygen at 1 MPa is connected to an empty cylinder of 3 L capacity, then during isothermal expansion of the gas the pressure in the cylinders will be equal to',
    questionKk: '1 МПа қысымда 12 л оттегі бар баллонды 3 л бос баллонмен жалғаса, изотермиялық кеңею кезінде баллондардағы қысым тең болады',
    questionRu: 'Если баллон, содержащий 12 л кислорода при давлении 1 МПа, соединить с пустым баллоном вместимостью 3 л, то в процессе изотермического расширения газа в баллонах установится давление, равное',
    options: ['4·10⁶ Pa', '8·10⁷ Pa', '0.8·10⁶ Pa', '10⁶ Pa', '4·10⁷ Pa'],
    optionsKk: ['4·10⁶ Па', '8·10⁷ Па', '0,8·10⁶ Па', '10⁶ Па', '4·10⁷ Па'],
    optionsRu: ['4·10⁶ Па', '8·10⁷ Па', '0,8·10⁶ Па', '10⁶ Па', '4·10⁷ Па'],
    correctAnswer: 2,
  },
  // Q6: Number of gold atoms in layer
  {
    id: 'ph6',
    question: 'The number of gold atoms in a layer of thickness 1 µm and area 20 cm² (M_Au = 197 g/mol, ρ_Au = 19.3 g/cm³, N_A = 6.02·10²³ mol⁻¹)',
    questionKk: 'Қалыңдығы 1 мкм, ауданы 20 см² алтын қабатындағы атомдар саны (M_Au = 197 г/моль, ρ_Au = 19,3 г/см³, N_A = 6,02·10²³ моль⁻¹)',
    questionRu: 'Число атомов золота в слое толщиной 1 мкм, площадью 20 см² (M_Au = 197 г/моль, ρ_Au = 19,3 г/см³, N_A = 6,02·10²³ моль⁻¹)',
    options: ['4.6·10¹⁷', '4.6·10¹⁸', '1.2·10¹⁹', '1.2·10²⁰', '12·10²⁰'],
    optionsKk: ['4,6·10¹⁷', '4,6·10¹⁸', '1,2·10¹⁹', '1,2·10²⁰', '12·10²⁰'],
    optionsRu: ['4,6·10¹⁷', '4,6·10¹⁸', '1,2·10¹⁹', '1,2·10²⁰', '12·10²⁰'],
    correctAnswer: 1,
  },
  // Q7: Curie temperature
  {
    id: 'ph7',
    question: 'Curie temperature is the temperature at which',
    questionKk: 'Кюри температурасы – бұл температура, онда',
    questionRu: 'Температура Кюри — это температура, при которой',
    options: ['magnetic properties of the substance disappear', 'magnetic properties of the substance are enhanced', 'vapor becomes saturated', 'vapor becomes unsaturated', 'the density of the substance increases'],
    optionsKk: ['заттың магниттік қасиеті жойылады', 'заттың магниттік қасиеті күшейеді', 'бу қаныған болады', 'бу қанымаған болады', 'заттың тығыздығы артады'],
    optionsRu: ['исчезают магнитные свойства вещества', 'усиливаются магнитные свойства вещества', 'пар становится насыщенным', 'пар становится ненасыщенным', 'увеличивается плотность вещества'],
    correctAnswer: 0,
  },
  // Q8: Force on current-carrying conductor in magnetic field (diagram: current out of page)
  {
    id: 'ph8',
    question: 'The figure shows the interaction of a magnetic field with current. The force acting on the current-carrying conductor is directed',
    questionKk: 'Суретте магнит өрісі мен токтың өзара әрекеттесуі көрсетілген. Токты өткізетін өткізгішке әсер ететін күш бағытталған',
    questionRu: 'На рисунке представлено взаимодействие магнитного поля с током. Сила, действующая на проводник с током, направлена',
    options: ['vertically downwards', 'vertically upwards', 'to the right', 'away from us', 'towards us'],
    optionsKk: ['тігінен төмен', 'тігінен жоғары', 'оңға', 'бізден қашық', 'бізге қарай'],
    optionsRu: ['вертикально вниз', 'вертикально вверх', 'вправо', 'от нас', 'к нам'],
    correctAnswer: 1,
    imageUrl: '/images/questions/ph8-magnetic.png',
  },
  // Q9: Photon mass given momentum
  {
    id: 'ph9',
    question: 'The mass of a photon whose momentum is 10⁻²⁸ kg·m/s (c = 3·10⁸ m/s)',
    questionKk: 'Импульсі 10⁻²⁸ кг·м/с болатын фотонның массасы (c = 3·10⁸ м/с)',
    questionRu: 'Масса фотона, импульс которого 10⁻²⁸ кг·м/с (c = 3·10⁸ м/с)',
    options: ['3.3·10³⁷ kg', '33·10⁻³⁷ kg', '0.33·10⁻³⁷ kg', '3.3·10⁻³⁷ kg', '330·10⁻³⁷ kg'],
    optionsKk: ['3,3·10³⁷ кг', '33·10⁻³⁷ кг', '0,33·10⁻³⁷ кг', '3,3·10⁻³⁷ кг', '330·10⁻³⁷ кг'],
    optionsRu: ['3,3·10³⁷ кг', '33·10⁻³⁷ кг', '0,33·10⁻³⁷ кг', '3,3·10⁻³⁷ кг', '330·10⁻³⁷ кг'],
    correctAnswer: 3,
  },
  // Q10: Lamps when K2 and K4 closed (with circuit diagram)
  {
    id: 'ph10',
    question: 'When switches K₂ and K₄ are closed, the lamps that will light up are',
    questionKk: 'K₂ және K₄ кілттері жабылғанда қандай шамдар жанады?',
    questionRu: 'При замыкании ключей K₂ и K₄ загорятся лампы',
    options: ['1, 2 and 3', '1, 2 and 5', '1, 2 and 4', '2, 3 and 4', '2, 4 and 5'],
    optionsKk: ['1, 2 және 3', '1, 2 және 5', '1, 2 және 4', '2, 3 және 4', '2, 4 және 5'],
    optionsRu: ['1, 2 и 3', '1, 2 и 5', '1, 2 и 4', '2, 3 и 4', '2, 4 и 5'],
    correctAnswer: 4,
    imageUrl: '/images/questions/ph10-circuit.png',
  },
  // Q11: Path and displacement from diagram (0.1 km, 60 m, 4000 cm, 20 m)
  {
    id: 'ph11',
    question: 'Path and displacement according to the given drawing (movements: 0.1 km right, 60 m down, 4000 cm left, 20 m down)',
    questionKk: 'Берілген сурет бойынша жол және орын ауыстыру (0,1 км оңға, 60 м төмен, 4000 см солға, 20 м төмен)',
    questionRu: 'Путь и перемещение по заданному рисунку',
    options: ['200 m; 5080 m', '4180 m; 200 m', '5080 m; 19600 m', '100 m; 200 m', '220 m; 100 m'],
    optionsKk: ['200 м; 5080 м', '4180 м; 200 м', '5080 м; 19600 м', '100 м; 200 м', '220 м; 100 м'],
    optionsRu: ['200 м; 5080 м', '4180 м; 200 м', '5080 м; 19600 м', '100 м; 200 м', '220 м; 100 м'],
    correctAnswer: 4,
    imageUrl: '/images/questions/ph11-path.png',
  },
  // Q12: Spring stiffness – block 300 g, μ = 0.3, stretch 2 cm, g = 10
  {
    id: 'ph12',
    question: 'If a block of mass 300 g moves uniformly on a horizontal surface with friction coefficient 0.3 and a spring stretches by 2 cm, then the spring stiffness is (g = 10 m/s²)',
    questionKk: '300 г массалы кірпіш көлденең бетте 0,3 үйкеліс коэффициентімен бірқалыпты қозғалғанда серіппе 2 см созылса, серіппе қаттылығы (g = 10 м/с²)',
    questionRu: 'Если при равномерном движении бруска массой 300 г по горизонтальной поверхности с коэффициентом трения 0,3 пружина растянулась на 2 см, то жёсткость пружины равна (g = 10 м/с²)',
    options: ['0.45 N/m', '4500 N/m', '4.5 N/m', '450 N/m', '45 N/m'],
    optionsKk: ['0,45 Н/м', '4500 Н/м', '4,5 Н/м', '450 Н/м', '45 Н/м'],
    optionsRu: ['0,45 Н/м', '4500 Н/м', '4,5 Н/м', '450 Н/м', '45 Н/м'],
    correctAnswer: 4,
  },
  // Q13: Steam turbine efficiency 60%, heater 427°C – refrigerator temp
  {
    id: 'ph13',
    question: 'A steam turbine has an efficiency of 60%; the heater temperature is 427°C. The refrigerator temperature is',
    questionKk: 'Бу турбинасының ПӘК-і 60%, жылытқыш температурасы 427°C. Суытқыш температурасы',
    questionRu: 'Паровая турбина имеет КПД 60%, при этом температура её нагревателя 427°C, а температура холодильника',
    options: ['2.8 K', '2800 K', '170 K', '280 K', '28 K'],
    optionsKk: ['2,8 К', '2800 К', '170 К', '280 К', '28 К'],
    optionsRu: ['2,8 К', '2800 К', '170 К', '280 К', '28 К'],
    correctAnswer: 3,
  },
  // Q14: Conductor in magnetic field – B to balance gravity
  {
    id: 'ph14',
    question: 'The current in a horizontally placed conductor of length 20 cm and mass 4 g is 10 A. The magnitude of magnetic field induction so that the force of gravity is balanced by the Ampere force is',
    questionKk: 'Ұзындығы 20 см, массасы 4 г көлденең өткізгіштегі ток 10 А. Ампер күші ауырлық күшін теңестіру үшін магнит индукциясының модулі',
    questionRu: 'Сила тока в горизонтально расположенном проводнике длиной 20 см и массой 4 г равна 10 А. Модуль индукции магнитного поля, в которое нужно поместить проводник, чтобы сила тяжести уравновесилась силой Ампера, равен',
    options: ['15 mT', '40 mT', '10 mT', '20 mT', '30 mT'],
    optionsKk: ['15 мТл', '40 мТл', '10 мТл', '20 мТл', '30 мТл'],
    optionsRu: ['15 мТл', '40 мТл', '10 мТл', '20 мТл', '30 мТл'],
    correctAnswer: 3,
  },
  // Q15: Two buckets balanced – wooden block in one
  {
    id: 'ph15',
    question: 'Two buckets filled to the brim with water are balanced on a lever scale. A wooden block is lowered into one bucket. The balance of the scales after some time',
    questionKk: 'Суға толы екі шелек таразыда теңдестірілген. Бір шелекке ағаш кірпіш салынады. Біраз уақыттан кейін теңдестік',
    questionRu: 'На двух чашах рычажных весов уравновешены два ведра, до краёв наполненные водой. В одно из вёдер опускают деревянный брусок. Равновесие весов через некоторое время',
    options: ['will be disturbed where the block is; mass of bucket increases', 'will be disturbed where the block is; volume of water decreases', 'will be disturbed where the block is; volume of water increases', 'will not change', 'will be disturbed where the block is; mass of water decreases'],
    optionsKk: ['кірпіш салынған жақта бұзылады; шелек массасы артады', 'кірпіш салынған жақта бұзылады; су көлемі азаяды', 'кірпіш салынған жақта бұзылады; су көлемі артады', 'өзгермейді', 'кірпіш салынған жақта бұзылады; су массасы азаяды'],
    optionsRu: ['нарушится, где брусок — масса ведра увеличится', 'нарушится, где брусок — объём воды уменьшится', 'нарушится, где брусок — объём воды увеличится', 'не изменится', 'нарушится, где брусок — масса воды уменьшится'],
    correctAnswer: 2,
  },
  // Q16: Harmonic oscillation – max acceleration
  {
    id: 'ph16',
    question: 'The displacement of a point in harmonic oscillations is x = 0.2 cos(2t + π/2) m. The maximum acceleration of the point is',
    questionKk: 'Гармоникалық тербелісте нүктенің орын ауыстыруы x = 0,2 cos(2t + π/2) м. Нүктенің максимал үдеуі',
    questionRu: 'Смещение точки при гармонических колебаниях выражено уравнением x = 0,2 cos(2t + π/2) м. Максимальное ускорение точки равно',
    options: ['0.02 m/s²', '0.2 m/s²', '0.8 m/s²', '0.4 m/s²', '0.01 m/s²'],
    optionsKk: ['0,02 м/с²', '0,2 м/с²', '0,8 м/с²', '0,4 м/с²', '0,01 м/с²'],
    optionsRu: ['0,02 м/с²', '0,2 м/с²', '0,8 м/с²', '0,4 м/с²', '0,01 м/с²'],
    correctAnswer: 2,
  },
  // Q17: Work of gas in isobaric process
  {
    id: 'ph17',
    question: 'The work of a gas in thermodynamics during an isobaric process is determined by the formula',
    questionKk: 'Изобаралық процесс кезінде термодинамикада газ жұмысы мына формуламен анықталады',
    questionRu: 'Работа газа в термодинамике при изобарном процессе определяется по формуле',
    options: ['A = p(V₂ − V₁)', 'A = Fs', 'A = Fs cos α', 'A = ΔW_p', 'A = E_k₂ − E_k₁'],
    optionsKk: ['A = p(V₂ − V₁)', 'A = Fs', 'A = Fs cos α', 'A = ΔW_p', 'A = E_k₂ − E_k₁'],
    optionsRu: ['A = p(V₂ − V₁)', 'A = Fs', 'A = Fs cos α', 'A = ΔW_p', 'A = E_k₂ − E_k₁'],
    correctAnswer: 0,
  },
  // Q18: Electron in field – distance to stop
  {
    id: 'ph18',
    question: 'An electron moves along the field lines of a uniform field of strength 120 V/m. If its initial speed is 1 Mm/s, the distance it will travel until it stops (e = −1.6·10⁻¹⁹ C, m_e = 9.1·10⁻³¹ kg)',
    questionKk: 'Электрон кернеулігі 120 В/м біртекті өріс силовые сызықтары бойынша қозғалады. Бастапқы жылдамдығы 1 Мм/с болса, ол тоқтағанша ұшатын қашықтық (е = −1,6·10⁻¹⁹ Кл, m_e = 9,1·10⁻³¹ кг)',
    questionRu: 'Электрон движется по направлению силовых линий однородного поля, напряжённость которого равна 120 В/м. Если его начальная скорость равна 1 Мм/с, то расстояние, которое он пролетит до полной остановки (е = −1,6·10⁻¹⁹ Кл, m_e = 9,1·10⁻³¹ кг)',
    options: ['12 cm', '24 mm', '4.8 cm', '24 cm', '1.2 mm'],
    optionsKk: ['12 см', '24 мм', '4,8 см', '24 см', '1,2 мм'],
    optionsRu: ['12 см', '24 мм', '4,8 см', '24 см', '1,2 мм'],
    correctAnswer: 3,
  },
  // Q19: Nearsighted – glasses −3 D, d₀ = 25 cm
  {
    id: 'ph19',
    question: 'A nearsighted person sees small objects well at distances up to 15 cm. If they wear glasses with optical power −3 D, they see objects well from a distance (d₀ = 25 cm)',
    questionKk: 'Жақын көру адам кішкене заттарды 15 см-ге дейін жақсы көреді. Ол −3 дптр оптикалық күші бар көзәйнек кисе, заттарды қандай қашықтықтан жақсы көреді (d₀ = 25 см)',
    questionRu: 'Близорукий человек мелкие предметы хорошо различает на расстоянии до 15 см. Если он носит очки с оптической силой −3 дптр, то он хорошо различает предметы с расстояния (d₀ = 25 см)',
    options: ['≈0.30 m', '≈0.25 m', '≈0.27 m', '≈0.35 m', '≈0.37 m'],
    optionsKk: ['≈0,30 м', '≈0,25 м', '≈0,27 м', '≈0,35 м', '≈0,37 м'],
    optionsRu: ['≈0,30 м', '≈0,25 м', '≈0,27 м', '≈0,35 м', '≈0,37 м'],
    correctAnswer: 2,
  },
  // Q20: Board across stream – phenomenon
  {
    id: 'ph20',
    question: 'A board is laid across a stream. The phenomenon associated with the change in the shape of the board when a boy walks over it is',
    questionKk: 'Ағаш арқылы тақтай салынған. Мальчик тақтайдан өткенде оның пішінінің өзгеруіне байланысты құбылыс',
    questionRu: 'Через ручей перекинута доска. Явление, связанное с изменением формы доски при прохождении мальчика через эту доску',
    options: ['deformation', 'modulation', 'recombination', 'generation', 'reverberation'],
    optionsKk: ['деформация', 'модуляция', 'рекомбинация', 'генерация', 'реверберация'],
    optionsRu: ['деформация', 'модуляция', 'рекомбинация', 'генерация', 'реверберация'],
    correctAnswer: 0,
  },
  // Q21–Q25: «Мёртвая петля» (Dead loop) – R = 2.5 m, g = 10 m/s², no friction (with diagram)
  {
    id: 'ph21',
    question: '«Dead loop»: loop radius 2.5 m, g = 10 m/s². Ibrahim\'s minimum speed at point B is',
    questionKk: '«Өлі цикл»: цикл радиусы 2,5 м, g = 10 м/с². Ибрагимнің В нүктесіндегі минимал жылдамдығы',
    questionRu: '«Мёртвая петля»: радиус петли 2,5 м, g = 10 м/с². Минимальная скорость Ибрагима в точке В',
    options: ['4 m/s', '16 m/s', '2 m/s', '5 m/s', '8 m/s'],
    optionsKk: ['4 м/с', '16 м/с', '2 м/с', '5 м/с', '8 м/с'],
    optionsRu: ['4 м/с', '16 м/с', '2 м/с', '5 м/с', '8 м/с'],
    correctAnswer: 3,
    imageUrl: '/images/questions/ph21-dead-loop.png',
  },
  {
    id: 'ph22',
    question: 'Minimum angular velocity of Ibragim at point B',
    questionKk: 'Ибрагимнің В нүктесіндегі минимал бұрыштық жылдамдығы',
    questionRu: 'Минимальная угловая скорость Ибрагима в точке В',
    options: ['2 rad/s', '3.2 rad/s', '4 rad/s', '1.6 rad/s', '10 rad/s'],
    optionsKk: ['2 рад/с', '3,2 рад/с', '4 рад/с', '1,6 рад/с', '10 рад/с'],
    optionsRu: ['2 рад/с', '3,2 рад/с', '4 рад/с', '1,6 рад/с', '10 рад/с'],
    correctAnswer: 0,
  },
  {
    id: 'ph23',
    question: 'Minimum speed of Ibragim on the Moon (g_Moon = g_Earth / 6)',
    questionKk: 'Ибрагимнің Айдағы минимал жылдамдығы (g_Ай = g_Жер / 6)',
    questionRu: 'Минимальная скорость Ибрагима на Луне',
    options: ['2 m/s', '4 m/s', '3 m/s', '1.6 m/s', '5 m/s'],
    optionsKk: ['2 м/с', '4 м/с', '3 м/с', '1,6 м/с', '5 м/с'],
    optionsRu: ['2 м/с', '4 м/с', '3 м/с', '1,6 м/с', '5 м/с'],
    correctAnswer: 0,
  },
  {
    id: 'ph24',
    question: 'Minimum ramp height for Ibragim to complete a full loop',
    questionKk: 'Ибрагимнің толық циклды орындауы үшін ең кіші трамплин биіктігі',
    questionRu: 'Наименьшая высота ската, чтобы Ибрагим мог совершить полную петлю',
    options: ['3.25 m', '5.35 m', '6.25 m', '3.35 m', '0.25 m'],
    optionsKk: ['3,25 м', '5,35 м', '6,25 м', '3,35 м', '0,25 м'],
    optionsRu: ['3,25 м', '5,35 м', '6,25 м', '3,35 м', '0,25 м'],
    correctAnswer: 2,
  },
  {
    id: 'ph25',
    question: 'Potential energy of the cyclist at the initial moment (mass of bicycle and Ibragim 80 kg)',
    questionKk: 'Бастапқы сәтте велосипедшінің потенциалдық энергиясы (велосипед пен Ибрагимнің массасы 80 кг)',
    questionRu: 'Потенциальная энергия велосипедиста в начальный момент (масса велосипеда и Ибрагима 80 кг)',
    options: ['1 kJ', '2 kJ', '5 kJ', '4 kJ', '3 kJ'],
    optionsKk: ['1 кДж', '2 кДж', '5 кДж', '4 кДж', '3 кДж'],
    optionsRu: ['1 кДж', '2 кДж', '5 кДж', '4 кДж', '3 кДж'],
    correctAnswer: 2,
  },
  // Q26–Q35: 8 options (A–H)
  {
    id: 'ph26',
    question: 'The dependence of the elastic force on spring deformation is F = 100x. To compress an undeformed spring by 5 cm, the work required is',
    questionKk: 'Серіппе деформациясынан серпімділік күшінің тәуелділігі F = 100x. Деформацияланбаған серіппені 5 см сығу үшін орындалатын жұмыс',
    questionRu: 'Зависимость модуля силы упругости от деформации пружины: F = 100x. Чтобы сжать недеформированную пружину на 5 см, надо совершить работу',
    options: ['250·10⁻³ J', '250 mJ', '125 mJ', '0.125 J', '0.25 J', '125·10⁻⁴ J', '250·10⁻⁴ J', '125·10⁻³ J'],
    optionsKk: ['250·10⁻³ Дж', '250 мДж', '125 мДж', '0,125 Дж', '0,25 Дж', '125·10⁻⁴ Дж', '250·10⁻⁴ Дж', '125·10⁻³ Дж'],
    optionsRu: ['250·10⁻³ Дж', '250 мДж', '125 мДж', '0,125 Дж', '0,25 Дж', '125·10⁻⁴ Дж', '250·10⁻⁴ Дж', '125·10⁻³ Дж'],
    correctAnswer: 3,
  },
  {
    id: 'ph27',
    question: 'The amount of substance in 1 kg of water (M_H₂O = 18·10⁻³ kg/mol)',
    questionKk: '1 кг судағы зат мөлшері (M_H₂O = 18·10⁻³ кг/моль)',
    questionRu: 'Количество вещества, содержащегося в 1 кг воды (M_H₂O = 18·10⁻³ кг/моль)',
    options: ['10 mol', '1.8 mol', '1800 mmol', '55.6 mol', '0.0556 kmol', '18 mol', '5.56 mol', '0.018 kmol'],
    optionsKk: ['10 моль', '1,8 моль', '1800 ммоль', '55,6 моль', '0,0556 кмоль', '18 моль', '5,56 моль', '0,018 кмоль'],
    optionsRu: ['10 моль', '1,8 моль', '1800 ммоль', '55,6 моль', '0,0556 кмоль', '18 моль', '5,56 моль', '0,018 кмоль'],
    correctAnswer: 3,
  },
  {
    id: 'ph28',
    question: 'A flat rectangular frame 25 cm × 60 cm is in a magnetic field of 2 T. If the magnetic induction vector makes an angle of 45° with the plane of the frame, the magnetic flux through the frame is (sin 45° = cos 45° = 0.7)',
    questionKk: '25 см × 60 см жазық тікбұрышты рамка 2 Тл индукциялы магнит өрісінде. Индукция векторы рамка жазықтығымен 45° бұрыш жасаса, рамканы тесіп өтетін магнит ағыны (sin 45° = cos 45° = 0,7)',
    questionRu: 'Плоская прямоугольная рама со сторонами 25 см и 60 см находится в магнитном поле с индукцией 2 Тл. Если вектор магнитной индукции составляет угол 45° с плоскостью рамки, то магнитный поток, пронизывающий рамку, равен (sin 45° = cos 45° = 0,7)',
    options: ['≈2.1·10⁻² Wb', '≈21·10⁻⁴ Wb', '≈21·10⁻² Wb', '≈30 Wb', '≈0.21 Wb', '≈30·10⁻² Wb', '≈21 Wb', '≈3·10⁻² Wb'],
    optionsKk: ['≈2,1·10⁻² Вб', '≈21·10⁻⁴ Вб', '≈21·10⁻² Вб', '≈30 Вб', '≈0,21 Вб', '≈30·10⁻² Вб', '≈21 Вб', '≈3·10⁻² Вб'],
    optionsRu: ['≈2,1·10⁻² Вб', '≈21·10⁻⁴ Вб', '≈21·10⁻² Вб', '≈30 Вб', '≈0,21 Вб', '≈30·10⁻² Вб', '≈21 Вб', '≈3·10⁻² Вб'],
    correctAnswer: 4,
  },
  {
    id: 'ph29',
    question: 'During nickel plating for 30 minutes, the current through the bath is 0.8 A. The mass of nickel deposited (k_Ni = 0.3·10⁻⁶ kg/C) is',
    questionKk: '30 минут никельдеу кезінде ванна арқылы өтетін ток 0,8 А. Электрод бетіне шөккен никель массасы (k_Ni = 0,3·10⁻⁶ кг/Кл)',
    questionRu: 'При никелировании детали в течение 30 минут ток, проходящий через ванну, 0,8 А. Масса никеля, выделившегося на поверхности электрода (k_Ni = 0,3·10⁻⁶ кг/Кл)',
    options: ['432·10⁻³ mg', '432·10⁻³ g', '4.32 g', '432 kg', '43.2 mg', '432 mg', '432·10⁻⁶ kg', '0.432 mg'],
    optionsKk: ['432·10⁻³ мг', '432·10⁻³ г', '4,32 г', '432 кг', '43,2 мг', '432 мг', '432·10⁻⁶ кг', '0,432 мг'],
    optionsRu: ['432·10⁻³ мг', '432·10⁻³ г', '4,32 г', '432 кг', '43,2 мг', '432 мг', '432·10⁻⁶ кг', '0,432 мг'],
    correctAnswer: 5,
  },
  {
    id: 'ph30',
    question: 'With a converging lens, an image of an object is obtained at its natural size. The object is located',
    questionKk: 'Жинағыш линза көмегімен заттың кескіні оның табиғи өлшемінде алынады. Зат орналасқан',
    questionRu: 'С помощью собирающей линзы получено изображение предмета в натуральную величину. На этом основании можно утверждать, что предмет расположен',
    options: ['between double and triple focal distance', 'at triple focal distance', 'at double focal distance', 'at the focal point', 'beyond double focal distance', 'between focal point and lens', 'between focal point and double focal distance', 'beyond triple focal distance'],
    optionsKk: ['екі есе фокустық қашықтық пен үш есе фокустық қашықтық арасында', 'үш есе фокустық қашықтықта', 'екі есе фокустық қашықтықта', 'фокуста', 'екі есе фокустық қашықтықтан алыс', 'фокус пен линза арасында', 'фокус пен екі есе фокус арасында', 'үш есе фокустық қашықтықтан алыс'],
    optionsRu: ['между двойным и тройным фокусным расстоянием', 'на тройном фокусном расстоянии', 'на двойном фокусном расстоянии', 'в фокусе линзы', 'за двойным фокусным расстоянием', 'между фокусом и линзой', 'между фокусом и двойным фокусным расстоянием', 'за тройным фокусным расстоянием'],
    correctAnswer: 2,
  },
  {
    id: 'ph31',
    question: 'A spring of stiffness 2·10⁵ N/m has an elongation of 0.002 m. The potential energy of the spring is',
    questionKk: 'Қаттылығы 2·10⁵ Н/м серіппенің созылуы 0,002 м. Серіппенің потенциалдық энергиясы',
    questionRu: 'Упругое удлинение пружины жёсткостью 2·10⁵ Н/м равно 0,002 м. Потенциальная энергия пружины равна',
    options: ['200 mJ', '100 mJ', '0.2 J', '500 mJ', '0.05 J', '400 mJ', '0.4 J', '0.1 J'],
    optionsKk: ['200 мДж', '100 мДж', '0,2 Дж', '500 мДж', '0,05 Дж', '400 мДж', '0,4 Дж', '0,1 Дж'],
    optionsRu: ['200 мДж', '100 мДж', '0,2 Дж', '500 мДж', '0,05 Дж', '400 мДж', '0,4 Дж', '0,1 Дж'],
    correctAnswer: 6,
  },
  {
    id: 'ph32',
    question: 'The graph of the change in state of a monatomic ideal gas is shown. If p₀ = 0.1 MPa and V₀ = 2 L, then its internal energy',
    questionKk: 'Бір атомды идеал газ күйінің өзгеру графигі көрсетілген. p₀ = 0,1 МПа, V₀ = 2 л болса, оның ішкі энергиясы',
    questionRu: 'График изменения состояния одноатомного идеального газа представлен на рисунке. Если p₀ = 0,1 МПа, а V₀ = 2 л, то его внутренняя энергия',
    options: ['increased by 5.25 kJ', 'decreased by 2.75 kJ', 'increased by 2.75·10³ J', 'increased by 1.05 kJ', 'decreased by 1.05 kJ', 'did not change', 'increased by 2.75 kJ', 'decreased by 5.25 kJ'],
    optionsKk: ['5,25 кДж-ге артты', '2,75 кДж-ге азайды', '2,75·10³ Дж-ге артты', '1,05 кДж-ге артты', '1,05 кДж-ге азайды', 'өзгерген жоқ', '2,75 кДж-ге артты', '5,25 кДж-ге азайды'],
    optionsRu: ['увеличилась на 5,25 кДж', 'уменьшилась на 2,75 кДж', 'увеличилась на 2,75·10³ Дж', 'увеличилась на 1,05 кДж', 'уменьшилась на 1,05 кДж', 'не изменилась', 'увеличилась на 2,75 кДж', 'уменьшилась на 5,25 кДж'],
    correctAnswer: 6,
  },
  {
    id: 'ph33',
    question: 'Substances whose magnetic permeability μ >> 1 are called',
    questionKk: 'Магниттік өтімділігі μ >> 1 заттар деп аталады',
    questionRu: 'Вещества, у которых магнитная проницаемость μ >> 1, называются',
    options: ['crystals', 'magnetics', 'dielectrics', 'diamagnetics', 'ferromagnetics', 'insulators', 'paramagnetics', 'isotopes'],
    optionsKk: ['кристалдар', 'магниттер', 'диэлектрликтер', 'диамагнетиктер', 'ферромагнетиктер', 'изоляторлар', 'парамагнетиктер', 'изотоптар'],
    optionsRu: ['кристаллы', 'магнетики', 'диэлектрики', 'диамагнетики', 'ферромагнетики', 'изоляторы', 'парамагнетики', 'изотопы'],
    correctAnswer: 4,
  },
  {
    id: 'ph34',
    question: 'The partial pressure of water vapor in air at 15°C was 1.02 kPa. The relative humidity of the air is (at t = 15°C, saturated vapor pressure = 1.7 kPa)',
    questionKk: '15°C-та ауадағы су буының парциалды қысымы 1,02 кПа болды. Ауаның салыстырмалы ылғалдылығы (t = 15°C кезінде қаныған бу қысымы = 1,7 кПа)',
    questionRu: 'Парциальное давление водяного пара в воздухе при 15°C было 1,02 кПа. Относительная влажность воздуха равна (при t = 15°C давление насыщенного пара = 1,7 кПа)',
    options: ['0.33', '0.4', '33%', '0.6', '0.5', '50%', '40%', '60%'],
    optionsKk: ['0,33', '0,4', '33%', '0,6', '0,5', '50%', '40%', '60%'],
    optionsRu: ['0,33', '0,4', '33%', '0,6', '0,5', '50%', '40%', '60%'],
    correctAnswer: 7,
  },
  {
    id: 'ph35',
    question: 'The power of yellow light to which the retina is sensitive is ≈1.7·10⁻¹⁷ W. For the light to be perceived, the number of photons falling on the retina per second is (λ = 600 nm, h = 6.62·10⁻³⁴ J·s, c = 3·10⁸ m/s)',
    questionKk: 'Көз торы сезімтал сары жарық сәулесінің қуаты ≈1,7·10⁻¹⁷ Вт. Жарықты сезу үшін әр секундта торға түсуі керек фотондар саны (λ = 600 нм, h = 6,62·10⁻³⁴ Дж·с, c = 3·10⁸ м/с)',
    questionRu: 'Мощность излучения жёлтого света, к которому чувствительна сетчатка глаза, составляет ≈1,7·10⁻¹⁷ Вт. Чтобы свет был воспринят, ежесекундно на сетчатку глаза должно падать (λ = 600 нм, h = 6,62·10⁻³⁴ Дж·с, c = 3·10⁸ м/с)',
    options: ['≈90 photons', '≈40 photons', '≈80 photons', '≈60 photons', '≈10 photons', '≈50 photons', '≈70 photons', '≈30 photons'],
    optionsKk: ['≈90 фотон', '≈40 фотон', '≈80 фотон', '≈60 фотон', '≈10 фотон', '≈50 фотон', '≈70 фотон', '≈30 фотон'],
    optionsRu: ['≈90 фотонов', '≈40 фотонов', '≈80 фотонов', '≈60 фотонов', '≈10 фотонов', '≈50 фотонов', '≈70 фотонов', '≈30 фотонов'],
    correctAnswer: 5,
  },
]

export const mathematics2023Questions: QuestionI18n[] = [
  {
    id: 'm1',
    question: 'Calculate: log₃9 + log₂16',
    questionKk: 'Есептеңіз: log₃9 + log₂16',
    questionRu: 'Вычислите: log₃9 + log₂16',
    options: ['1', '6', '2', '5', '4'],
    optionsKk: ['1', '6', '2', '5', '4'],
    optionsRu: ['1', '6', '2', '5', '4'],
    correctAnswer: 1,
  },
  {
    id: 'm2',
    question: 'Solve the equation: (x² − x − 2) / (x + 1)² = 0',
    questionKk: 'Теңдеуді шешіңіз: (x² − x − 2) / (x + 1)² = 0',
    questionRu: 'Решите уравнение: (x² − x − 2) / (x + 1)² = 0',
    options: ['1; −1/2', '0; 1', '2', '−1', '2; −1'],
    optionsKk: ['1; −1/2', '0; 1', '2', '−1', '2; −1'],
    optionsRu: ['1; −1/2', '0; 1', '2', '−1', '2; −1'],
    correctAnswer: 2,
  },
  {
    id: 'm3',
    question: 'Solve the system: (1/3)^(3x) · (1/3)^(−y) = 1/9 and log₅(10x) − log₅(y) = 1',
    questionKk: 'Теңдеулер жүйесін шешіңіз: (1/3)^(3x)·(1/3)^(−y)=1/9 және log₅(10x)−log₅(y)=1',
    questionRu: 'Решите систему уравнений: (1/3)^(3x)·(1/3)^(−y)=1/9 и log₅(10x)−log₅(y)=1',
    options: ['(2; 4)', '(8; 2)', '(4; 1)', '(1; 5)', '(5; 4)'],
    optionsKk: ['(2; 4)', '(8; 2)', '(4; 1)', '(1; 5)', '(5; 4)'],
    optionsRu: ['(2; 4)', '(8; 2)', '(4; 1)', '(1; 5)', '(5; 4)'],
    correctAnswer: 0,
  },
  {
    id: 'm4',
    question: 'Find the larger of two numbers if their arithmetic mean is 9 and the difference of their squares is 72.',
    questionKk: 'Екі санның орташа арифметикалық мәні 9, квадраттарының айырмасы 72 болса, үлкенін табыңыз.',
    questionRu: 'Найдите большее из двух чисел, если их среднее арифметическое равно 9, а разность их квадратов равна 72.',
    options: ['8', '12', '10', '9', '11'],
    optionsKk: ['8', '12', '10', '9', '11'],
    optionsRu: ['8', '12', '10', '9', '11'],
    correctAnswer: 4,
  },
  {
    id: 'm5',
    question: 'Solve the inequality: |x² + 6x| ≤ 0',
    questionKk: 'Теңсіздікті шешіңіз: |x² + 6x| ≤ 0',
    questionRu: 'Решите неравенство: |x² + 6x| ≤ 0',
    options: ['{−6; 0}', '(−∞; −6] ∪ [0; +∞)', '(−∞; −6) ∪ (0; +∞)', '{−6; 1}', '{0; 6}'],
    optionsKk: ['{−6; 0}', '(−∞; −6] ∪ [0; +∞)', '(−∞; −6) ∪ (0; +∞)', '{−6; 1}', '{0; 6}'],
    optionsRu: ['{−6; 0}', '(−∞; −6] ∪ [0; +∞)', '(−∞; −6) ∪ (0; +∞)', '{−6; 1}', '{0; 6}'],
    correctAnswer: 0,
  },
  {
    id: 'm6',
    question: 'Find the solution to the system of inequalities: (7x − 2)/(x − 3) ≥ 0 and (5x + 1)/(6 − x) ≤ 1',
    questionKk: 'Теңсіздіктер жүйесінің шешімін табыңыз: (7x−2)/(x−3) ≥ 0 және (5x+1)/(6−x) ≤ 1',
    questionRu: 'Найдите решение системы неравенств: (7x−2)/(x−3) ≥ 0 и (5x+1)/(6−x) ≤ 1',
    options: ['(−∞; 3] ∪ (6; +∞)', '(−∞; 2/7] ∪ (6; +∞)', '[2/3; 6]', '(−∞; 2/3) ∪ (6; +∞)', '(3; 6)'],
    optionsKk: ['(−∞; 3] ∪ (6; +∞)', '(−∞; 2/7] ∪ (6; +∞)', '[2/3; 6]', '(−∞; 2/3) ∪ (6; +∞)', '(3; 6)'],
    optionsRu: ['(−∞; 3] ∪ (6; +∞)', '(−∞; 2/7] ∪ (6; +∞)', '[2/3; 6]', '(−∞; 2/3) ∪ (6; +∞)', '(3; 6)'],
    correctAnswer: 4,
  },
  {
    id: 'm7',
    question: 'Geometric progression {b_n} is increasing; b₂ = 4, b₄ = 36. Find b₅.',
    questionKk: 'Геометриялық прогрессия {b_n} өсулі, b₂ = 4, b₄ = 36. b₅ табыңыз.',
    questionRu: 'Геометрическая прогрессия {b_n} — возрастающая, b₂ = 4, b₄ = 36. Найдите b₅.',
    options: ['54', '122', '81', '36', '108'],
    optionsKk: ['54', '122', '81', '36', '108'],
    optionsRu: ['54', '122', '81', '36', '108'],
    correctAnswer: 4,
  },
  {
    id: 'm8',
    question: 'Chemical reaction obeys H(t) = 5 ln t + t². Find the rate of reaction at t = 2.',
    questionKk: 'Химиялық реакция H(t) = 5 ln t + t² заңына бағынады. t = 2 кезінде реакция жылдамдығын табыңыз.',
    questionRu: 'Химическая реакция подчиняется закону H(t) = 5 ln t + t². Найдите скорость реакции в момент t = 2.',
    options: ['4.5', '6', '4', '6.5', '5'],
    optionsKk: ['4,5', '6', '4', '6,5', '5'],
    optionsRu: ['4,5', '6', '4', '6,5', '5'],
    correctAnswer: 3,
  },
  {
    id: 'm9',
    question: 'A circle inscribed in an isosceles triangle divides one lateral side at the point of tangency into segments of length 15 and 2 (from the vertex). Find the length of the base.',
    questionKk: 'Тең бүйірлі үшбұрышқа іштей сызылған шеңбер бүйір қабырғаны жанасу нүктесінде 15 және 2 кесінділерге бөледі. Табанының ұзындығын табыңыз.',
    questionRu: 'Окружность, вписанная в равнобедренный треугольник, делит одну из боковых сторон в точке касания на отрезки длиной 15 и 2. Найдите длину основания.',
    options: ['7', '4', '6', '2', '8'],
    optionsKk: ['7', '4', '6', '2', '8'],
    optionsRu: ['7', '4', '6', '2', '8'],
    correctAnswer: 4,
  },
  {
    id: 'm10',
    question: 'Find the height of a pyramid each of whose lateral edges is 10 cm and whose base is a square with side 6√2 cm.',
    questionKk: 'Әр бүйір қыры 10 см, табаны қабырғасы 6√2 см квадрат пирамиданың биіктігін табыңыз.',
    questionRu: 'Найдите высоту пирамиды, каждое боковое ребро которой равно 10 см и в основании квадрат со стороной 6√2 см.',
    options: ['8√2 cm', '8 cm', '6 cm', '6√2 cm', '12 cm'],
    optionsKk: ['8√2 см', '8 см', '6 см', '6√2 см', '12 см'],
    optionsRu: ['8√2 см', '8 см', '6 см', '6√2 см', '12 см'],
    correctAnswer: 1,
  },
  {
    id: 'm11',
    question: 'In an arithmetic progression a₁ = −2, d = 16. Find the term number that equals 174.',
    questionKk: 'Арифметикалық прогрессияда a₁ = −2, d = 16. 174-ке тең мүшенің нөмірін табыңыз.',
    questionRu: 'В арифметической прогрессии a₁ = −2, d = 16, найдите номер члена, равного 174.',
    options: ['15', '14', '12', '13', '10'],
    optionsKk: ['15', '14', '12', '13', '10'],
    optionsRu: ['15', '14', '12', '13', '10'],
    correctAnswer: 2,
  },
  {
    id: 'm12',
    question: 'Find the value of (cos(5π/12) + cos(π/12)) · (sin(π/12) − sin(5π/12))',
    questionKk: '(cos(5π/12) + cos(π/12)) · (sin(π/12) − sin(5π/12)) өрнегінің мәнін табыңыз.',
    questionRu: 'Найдите значение выражения (cos(5π/12) + cos(π/12)) · (sin(π/12) − sin(5π/12))',
    options: ['−√3/2', '1', '√2/2', '√3', '−√6/2'],
    optionsKk: ['−√3/2', '1', '√2/2', '√3', '−√6/2'],
    optionsRu: ['−√3/2', '1', '√2/2', '√3', '−√6/2'],
    correctAnswer: 0,
  },
  {
    id: 'm13',
    question: 'Solve the system of inequalities: 2sin 2x + √2 ≥ 0 and 2cos 2x − 1 ≤ 0',
    questionKk: 'Теңсіздіктер жүйесін шешіңіз: 2sin 2x + √2 ≥ 0 және 2cos 2x − 1 ≤ 0',
    questionRu: 'Решите систему неравенств: 2sin 2x + √2 ≥ 0 и 2cos 2x − 1 ≤ 0',
    options: ['[π/3 + 2πn; 5π/4 + 2πn)', '[π/6 + πn; 5π/8 + πn)', '[π/6 + πn; 5π/8 + πn]', '(π/3 + 2πn; 5π/4 + 2πn]', '(π/6 + πn; 5π/8 + πn]'],
    optionsKk: ['[π/3 + 2πn; 5π/4 + 2πn)', '[π/6 + πn; 5π/8 + πn)', '[π/6 + πn; 5π/8 + πn]', '(π/3 + 2πn; 5π/4 + 2πn]', '(π/6 + πn; 5π/8 + πn]'],
    optionsRu: ['[π/3 + 2πn; 5π/4 + 2πn)', '[π/6 + πn; 5π/8 + πn)', '[π/6 + πn; 5π/8 + πn]', '(π/3 + 2πn; 5π/4 + 2πn]', '(π/6 + πn; 5π/8 + πn]'],
    correctAnswer: 1,
  },
  {
    id: 'm14',
    question: 'Indicate one antiderivative for f(x) = −6/x, for x > 0',
    questionKk: 'x > 0 үшін f(x) = −6/x функциясының бір алғашқы функциясын көрсетіңіз.',
    questionRu: 'Укажите одну из первообразных для функции f(x) = −6/x при x > 0',
    options: ['F(x) = (1/6)ln x', 'F(x) = ln x', 'F(x) = 6 ln x', 'F(x) = −6 ln x', 'F(x) = −(1/6)ln x'],
    optionsKk: ['F(x) = (1/6)ln x', 'F(x) = ln x', 'F(x) = 6 ln x', 'F(x) = −6 ln x', 'F(x) = −(1/6)ln x'],
    optionsRu: ['F(x) = (1/6)ln x', 'F(x) = ln x', 'F(x) = 6 ln x', 'F(x) = −6 ln x', 'F(x) = −(1/6)ln x'],
    correctAnswer: 3,
  },
  {
    id: 'm15',
    question: 'Find angle B of triangle ABC if A(1;1), B(4;1), and C(4;5)',
    questionKk: 'A(1;1), B(4;1), C(4;5) болса, АВС үшбұрышының В бұрышын табыңыз.',
    questionRu: 'Найдите угол B треугольника ABC, если A(1;1), B(4;1) и C(4;5)',
    options: ['120°', '90°', '30°', '60°', '135°'],
    optionsKk: ['120°', '90°', '30°', '60°', '135°'],
    optionsRu: ['120°', '90°', '30°', '60°', '135°'],
    correctAnswer: 1,
  },
  {
    id: 'm16',
    question: 'Simplify: (sin 3α / sin α) − (cos 3α / cos α)',
    questionKk: 'Жеңілдетіңіз: (sin 3α / sin α) − (cos 3α / cos α)',
    questionRu: 'Упростите: (sin 3α / sin α) − (cos 3α / cos α)',
    options: ['0', '1', '2', '−1', '3'],
    optionsKk: ['0', '1', '2', '−1', '3'],
    optionsRu: ['0', '1', '2', '−1', '3'],
    correctAnswer: 2,
  },
  {
    id: 'm17',
    question: 'Find the length of segment AB if A(2;4) and B(4;6).',
    questionKk: 'A(2;4), B(4;6) болса, АВ кесіндісінің ұзындығын табыңыз.',
    questionRu: 'Найдите длину отрезка AB, если A(2;4), B(4;6).',
    options: ['2', '√2', '2√2', '8', '4'],
    optionsKk: ['2', '√2', '2√2', '8', '4'],
    optionsRu: ['2', '√2', '2√2', '8', '4'],
    correctAnswer: 2,
  },
  {
    id: 'm18',
    question: 'The product of the digits of a two-digit number is 13 less than the number. If 45 is added to it, the result is the number with digits reversed. Find this number.',
    questionKk: 'Екі таңбалы санның цифрлары көбейтіндісі санның өзінен 13-ке кем. Оған 45 қосса, цифрлары кері ретпен жазылған сан шығады. Осы санды табыңыз.',
    questionRu: 'Произведение цифр двузначного числа на 13 меньше самого числа. Если к данному числу прибавить 45, то получится число, записанное теми же цифрами, но в обратном порядке. Найдите это число.',
    options: ['36 or 49', '27 or 49', '49 or 63', '63 or 72', '27 or 36'],
    optionsKk: ['36 немесе 49', '27 немесе 49', '49 немесе 63', '63 немесе 72', '27 немесе 36'],
    optionsRu: ['36 или 49', '27 или 49', '49 или 63', '63 или 72', '27 или 36'],
    correctAnswer: 0,
  },
  {
    id: 'm19',
    question: 'Solve the system: √(4x−7) < x and √(x+5) + √(5−x) > 4. How many integer solutions?',
    questionKk: 'Жүйені шешіңіз: √(4x−7) < x және √(x+5) + √(5−x) > 4. Бүтін шешімдер саны қанша?',
    questionRu: 'Решите систему неравенств и укажите количество целых решений: √(4x−7) < x и √(x+5) + √(5−x) > 4',
    options: ['4', '2', '1', '3', '5'],
    optionsKk: ['4', '2', '1', '3', '5'],
    optionsRu: ['4', '2', '1', '3', '5'],
    correctAnswer: 0,
  },
  {
    id: 'm20',
    question: 'Triangular pyramid: base ABC with AB = BC = 10 cm, AC = 12 cm; height 5 cm. Find the volume.',
    questionKk: 'Табаны ABC (AB = BC = 10 см, AC = 12 см), биіктігі 5 см пирамиданың көлемін табыңыз.',
    questionRu: 'Основание пирамиды — треугольник ABC, AB = BC = 10 см, AC = 12 см. Высота пирамиды 5 см. Найдите объём пирамиды.',
    options: ['72 cm³', '40 cm³', '86 cm³', '80 cm³', '60 cm³'],
    optionsKk: ['72 см³', '40 см³', '86 см³', '80 см³', '60 см³'],
    optionsRu: ['72 см³', '40 см³', '86 см³', '80 см³', '60 см³'],
    correctAnswer: 3,
  },
  {
    id: 'm21',
    question: 'Context: 3 economists, 5 managers, 4 programmers applied. For 3 new programmers there are 4 workstations. In how many ways can they choose their workstations?',
    questionKk: 'Контекст: 3 экономист, 5 менеджер, 4 программист жіберді. 3 жаңа программистке 4 жұмыс орны бар. Жаңадан келгендер жұмыс орнын қанша әдіспен таңдай алады?',
    questionRu: 'Для трудоустройства прислали 3 экономиста, 5 менеджеров, 4 программиста. Для 3 новых программистов имеется 4 рабочих места. Укажите количество способов выбора рабочего места.',
    options: ['26', '21', '18', '15', '24'],
    optionsKk: ['26', '21', '18', '15', '24'],
    optionsRu: ['26', '21', '18', '15', '24'],
    correctAnswer: 4,
  },
  {
    id: 'm22',
    question: 'The enterprise needs 3 programmers. In how many ways can they be chosen (from the 4 who applied)?',
    questionKk: 'Кәсіпорынға 3 программист керек. Оларды қанша әдіспен таңдауға болады?',
    questionRu: 'Предприятию требуется 3 программиста. Укажите количество способов, которыми их можно выбрать.',
    options: ['2', '6', '8', '4', '5'],
    optionsKk: ['2', '6', '8', '4', '5'],
    optionsRu: ['2', '6', '8', '4', '5'],
    correctAnswer: 3,
  },
  {
    id: 'm23',
    question: 'They invited 2 economists or 3 managers for interviews, but allocated 5 fewer days than the number of possible ways for such a choice. How many days were allocated?',
    questionKk: 'Сұхбатқа 2 экономист немесе 3 менеджер шақырылды, бірақ мұндай таңдау әдістерінің санынан 5 күн аз бөлінді. Сұхбатқа қанша күн бөлінді?',
    questionRu: 'На собеседования приглашали 2 экономиста или 3 менеджера, но выделили на 5 дней меньше, чем количество возможных способов такого выбора. Укажите количество дней.',
    options: ['5 days', '18 days', '13 days', '25 days', '8 days'],
    optionsKk: ['5 күн', '18 күн', '13 күн', '25 күн', '8 күн'],
    optionsRu: ['5 дней', '18 дней', '13 дней', '25 дней', '8 дней'],
    correctAnswer: 2,
  },
  {
    id: 'm24',
    question: 'The enterprise hires 3 managers; 5 firms must be assigned to them. In how many ways can 5 firms be distributed among 3 employees?',
    questionKk: 'Кәсіпорын 3 менеджерді қабылдайды; оларға 5 фирманы бекіту керек. 5 фирманы 3 қызметкер арасында қанша әдіспен бөлуге болады?',
    questionRu: 'Предприятие принимает 3 менеджеров, за которыми должны закрепить 5 фирм. Сколькими способами можно распределить 5 фирм между 3 работниками?',
    options: ['150', '45', '20', '243', '185'],
    optionsKk: ['150', '45', '20', '243', '185'],
    optionsRu: ['150', '45', '20', '243', '185'],
    correctAnswer: 0,
  },
  {
    id: 'm25',
    question: 'Calculate the probability that of all applicants, 2 economists, 3 managers, and 3 programmers get employed (round to hundredths).',
    questionKk: 'Резюме жібергендердің ішінен 2 экономист, 3 менеджер және 3 программист жұмысқа орналасу ықтималдығын есептеңіз (жүздікке дейін).',
    questionRu: 'Вычислите вероятность, что из всех подавших резюме трудоустроятся 2 экономиста, 3 менеджера и 3 программиста (округлите до сотых).',
    options: ['0.12', '0.24', '0.15', '0.21', '0.28'],
    optionsKk: ['0,12', '0,24', '0,15', '0,21', '0,28'],
    optionsRu: ['0,12', '0,24', '0,15', '0,21', '0,28'],
    correctAnswer: 0,
  },
  {
    id: 'm26',
    question: 'Indicate the expressions whose value equals √3 (one or more correct)',
    questionKk: 'Мәні √3-ке тең өрнектерді көрсетіңіз (бір немесе бірнеше дұрыс жауап)',
    questionRu: 'Укажите выражения, значения которых численно равны √3',
    options: ['−2 cos(π/6)', 'sin(π/3)', 'tg 45°', '2 tg 30°', 'cos 120°', '−ctg(π/3)', '2 sin 60°', 'ctg 30°'],
    optionsKk: ['−2 cos(π/6)', 'sin(π/3)', 'tg 45°', '2 tg 30°', 'cos 120°', '−ctg(π/3)', '2 sin 60°', 'ctg 30°'],
    optionsRu: ['−2 cos(π/6)', 'sin(π/3)', 'tg 45°', '2 tg 30°', 'cos 120°', '−ctg(π/3)', '2 sin 60°', 'ctg 30°'],
    correctAnswer: 1,
  },
  {
    id: 'm27',
    question: 'The roots of the equation (x² + 2)² − 6(x² + 2) − 7 = 0 are',
    questionKk: '(x² + 2)² − 6(x² + 2) − 7 = 0 теңдеуінің түбірлері',
    questionRu: 'Корнями уравнения (x² + 2)² − 6(x² + 2) − 7 = 0 являются',
    options: ['−1', '√3', '√5', '1', '−3', '−√5', '7', '−√3'],
    optionsKk: ['−1', '√3', '√5', '1', '−3', '−√5', '7', '−√3'],
    optionsRu: ['−1', '√3', '√5', '1', '−3', '−√5', '7', '−√3'],
    correctAnswer: 2,
  },
  {
    id: 'm28',
    question: 'Find (x + y) where (x; y) solves x = y − π/2, tg x + 2 ctg y = 1, if (x + y) ∈ [−2π; 2π]',
    questionKk: '(x; y) жүйенің шешімі: x = y − π/2, tg x + 2 ctg y = 1. (x + y) ∈ [−2π; 2π] болса, (x + y) табыңыз.',
    questionRu: 'Найдите значение (x + y), где (x; y) — решение системы x = y − π/2, tg x + 2 ctg y = 1, если (x + y) ∈ [−2π; 2π]',
    options: ['2π', 'π', '−π', '−2π', '−π/2', 'π/2', '180°', '0°'],
    optionsKk: ['2π', 'π', '−π', '−2π', '−π/2', 'π/2', '180°', '0°'],
    optionsRu: ['2π', 'π', '−π', '−2π', '−π/2', 'π/2', '180°', '0°'],
    correctAnswer: 0,
  },
  {
    id: 'm29',
    question: 'Two consecutive natural numbers of the form 3n have sum 21 and product 108. Indicate these numbers.',
    questionKk: '3n түріндегі екі өзара жанасар натурал санның қосындысы 21, көбейтіндісі 108. Осы сандарды көрсетіңіз.',
    questionRu: 'Сумма двух последовательных натуральных чисел вида 3n равна 21, а их произведение 108. Укажите эти числа.',
    options: ['12', '14', '13', '9', '10', '11', '8', '7'],
    optionsKk: ['12', '14', '13', '9', '10', '11', '8', '7'],
    optionsRu: ['12', '14', '13', '9', '10', '11', '8', '7'],
    correctAnswer: 0,
  },
  {
    id: 'm30',
    question: 'The solution set of the inequality 3x − 2(4 + 5x) ≥ 2(5 − x) is the interval',
    questionKk: '3x − 2(4 + 5x) ≥ 2(5 − x) теңсіздігінің шешімдер жиыны',
    questionRu: 'Решением неравенства 3x − 2(4 + 5x) ≥ 2(5 − x) является промежуток',
    options: ['[−3.6; +∞)', '(−∞; 3.6]', '(−∞; −3.6]', 'x ≤ 3.6', '[3.6; +∞)', 'x ≥ 3.6', 'x ≥ −3.6', 'x ≤ −3.6'],
    optionsKk: ['[−3,6; +∞)', '(−∞; 3,6]', '(−∞; −3,6]', 'x ≤ 3,6', '[3,6; +∞)', 'x ≥ 3,6', 'x ≥ −3,6', 'x ≤ −3,6'],
    optionsRu: ['[−3,6; +∞)', '(−∞; 3,6]', '(−∞; −3,6]', 'x ≤ 3,6', '[3,6; +∞)', 'x ≥ 3,6', 'x ≥ −3,6', 'x ≤ −3,6'],
    correctAnswer: 4,
  },
  {
    id: 'm31',
    question: 'Find (x + y) where (x; y) solves x² − 5y² + 4 = 0 and log₄x − log₄y = 0',
    questionKk: 'x² − 5y² + 4 = 0 және log₄x − log₄y = 0 жүйесінің шешімі (x; y) болса, (x + y) табыңыз.',
    questionRu: 'Найдите сумму (x + y), где (x; y) — решение системы x² − 5y² + 4 = 0 и log₄x − log₄y = 0',
    options: ['0.5', '1/4', '0.25', '2', '1', '4', '1/8', '(1/2)^(−1)'],
    optionsKk: ['0,5', '1/4', '0,25', '2', '1', '4', '1/8', '(1/2)^(−1)'],
    optionsRu: ['0,5', '1/4', '0,25', '2', '1', '4', '1/8', '(1/2)^(−1)'],
    correctAnswer: 4,
  },
  {
    id: 'm32',
    question: 'The roots of f′(x) = 0, where f(x) = x³ − 3x² + 15',
    questionKk: 'f(x) = x³ − 3x² + 15 болса, f′(x) = 0 теңдеуінің түбірлері',
    questionRu: 'Корни уравнения f′(x) = 0, где f(x) = x³ − 3x² + 15',
    options: ['−4', '0', '2', '−3', '4', '−2', '1', '−1'],
    optionsKk: ['−4', '0', '2', '−3', '4', '−2', '1', '−1'],
    optionsRu: ['−4', '0', '2', '−3', '4', '−2', '1', '−1'],
    correctAnswer: 2,
  },
  {
    id: 'm33',
    question: 'The circumference of a city flowerbed is 42 m. Find its diameter and area (round π to integers).',
    questionKk: 'Қала гүлзарының шеңбер ұзындығы 42 м. Диаметрі мен ауданын табыңыз (π-ны бүтінге дейін).',
    questionRu: 'Длина окружности городской клумбы равна 42 м. Найдите диаметр и площадь (π округлите до целых).',
    options: ['12 cm', '36 cm²', '147 cm²', '14 cm', '210 cm²', '160 cm²', '3.5 cm', '7 cm'],
    optionsKk: ['12 см', '36 см²', '147 см²', '14 см', '210 см²', '160 см²', '3,5 см', '7 см'],
    optionsRu: ['12 см', '36 см²', '147 см²', '14 см', '210 см²', '160 см²', '3,5 см', '7 см'],
    correctAnswer: 2,
  },
  {
    id: 'm34',
    question: 'Indicate all integers from the domain of y = arctg(3x + 1) + 1/√(−x² + 10x − 21)',
    questionKk: 'y = arctg(3x + 1) + 1/√(−x² + 10x − 21) функциясының анықталу облысынан барлық бүтін сандарды көрсетіңіз.',
    questionRu: 'Укажите все целые числа из области определения функции y = arctg(3x + 1) + 1/√(−x² + 10x − 21)',
    options: ['3', '2', '5', '6', '4', '7', '8', '1'],
    optionsKk: ['3', '2', '5', '6', '4', '7', '8', '1'],
    optionsRu: ['3', '2', '5', '6', '4', '7', '8', '1'],
    correctAnswer: 4,
  },
  {
    id: 'm35',
    question: 'Through the vertex of an acute angle of right triangle ABC (right angle at C), line AD is drawn perpendicular to the plane of the triangle. Find the distance from D to B if AC = 8, BC = 9, AD = 10.',
    questionKk: 'Тік бұрышты АВС үшбұрышы (С тік бұрыш) сүйір бұрышы төбесі арқылы үшбұрыш жазықтығына перпендикуляр AD түзуі жүргізілген. АС = 8, ВС = 9, AD = 10 болса, D-дан B-ге дейінгі қашықтықты табыңыз.',
    questionRu: 'Через вершину острого угла прямоугольного треугольника ABC с прямым углом C проведена прямая AD, перпендикулярная плоскости треугольника. Найдите расстояние от D до B, если AC = 8, BC = 9, AD = 10.',
    options: ['5√7', '175', '7√5', '√145', '√125', '√245', '5√5', '132'],
    optionsKk: ['5√7', '175', '7√5', '√145', '√125', '√245', '5√5', '132'],
    optionsRu: ['5√7', '175', '7√5', '√145', '√125', '√245', '5√5', '132'],
    correctAnswer: 5,
  },
]

/** Pick localized question text and options for display */
export function getLocalizedQuestion(
  q: QuestionI18n,
  lang: Lang
): { question: string; options: string[] } {
  const question =
    lang === 'kk' ? q.questionKk : lang === 'ru' ? q.questionRu : q.question
  const options =
    lang === 'kk' ? q.optionsKk : lang === 'ru' ? q.optionsRu : q.options
  return { question, options }
}

/** Convert i18n question to simple format for a given language (for API/display) */
export function questionToSimple(
  q: QuestionI18n,
  lang: Lang
): { id: string; question: string; options: string[]; correctAnswer: number } {
  const { question, options } = getLocalizedQuestion(q, lang)
  return { id: q.id, question, options, correctAnswer: q.correctAnswer }
}
